// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyq9bfRqQ0HhuKUU5Nvv590q0qzyLkk40',
    appId: '1:832011960003:web:a21423067e279158656c76',
    messagingSenderId: '832011960003',
    projectId: 'test-21d25',
    authDomain: 'test-21d25.firebaseapp.com',
    storageBucket: 'test-21d25.firebasestorage.app',
    measurementId: 'G-9R7PNMTGRY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7i1SkaWODdvRSUrQhEMO68Cm7Jb8E-Ew',
    appId: '1:832011960003:android:fff31bcc3f35cb85656c76',
    messagingSenderId: '832011960003',
    projectId: 'test-21d25',
    storageBucket: 'test-21d25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvh9kp4RxATpTD09q9QlaGNZgXAuIOPcE',
    appId: '1:832011960003:ios:d6c25b717565ed4d656c76',
    messagingSenderId: '832011960003',
    projectId: 'test-21d25',
    storageBucket: 'test-21d25.firebasestorage.app',
    iosBundleId: 'com.example.cocinagame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvh9kp4RxATpTD09q9QlaGNZgXAuIOPcE',
    appId: '1:832011960003:ios:d6c25b717565ed4d656c76',
    messagingSenderId: '832011960003',
    projectId: 'test-21d25',
    storageBucket: 'test-21d25.firebasestorage.app',
    iosBundleId: 'com.example.cocinagame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyq9bfRqQ0HhuKUU5Nvv590q0qzyLkk40',
    appId: '1:832011960003:web:09a6108d7dbe774e656c76',
    messagingSenderId: '832011960003',
    projectId: 'test-21d25',
    authDomain: 'test-21d25.firebaseapp.com',
    storageBucket: 'test-21d25.firebasestorage.app',
    measurementId: 'G-BPQCZZNPKS',
  );
}
